feat: [CO-335] Add Certbot dryrun command
Zextras/carbonio-core-utils pull request #33
Opened 2023-02-09 11:53 UTC by aheeva-yuliya

2023-02-10 13:33 UTC, frisonisland approved these changes

2023-02-13 09:00 UTC, Polpetta requested changes
There are some minor fixes

Please use https://www.shellcheck.net/ to check bash/sh scripts!

2023-02-13 09:00 UTC, Polpetta commented on src/libexec/certbot
> +ACTION=$1
This doesn't break if an action has a space 
```suggestion
ACTION="${1}"
```

2023-02-13 09:00 UTC, Polpetta commented on src/libexec/certbot
> +  echo "$0 must be run as user zextras"
Always better to use bash variables with `${variable_name}` to avoid problems
```suggestion
  echo "${0} must be run as user zextras"
```

2023-02-13 09:00 UTC, Polpetta commented on src/libexec/certbot
> +if [ "$ACTION" = "certonly" ]; then
```suggestion
if [ "${ACTION}" = "certonly" ]; then
```

2023-02-13 10:36 UTC, aheeva-yuliya commented
> Please use https://www.shellcheck.net/ to check bash/sh scripts!

ok thank you

2023-02-13 10:42 UTC, Polpetta approved these changes

2023-02-13 10:51 UTC, keshavbhatt approved these changes
lgtm

2023-02-14 10:38 UTC, merged