feat: [CO-656] make zmantivirusctl handle also clamav only setup
Zextras/carbonio-core-utils pull request #40
Opened 2023-03-27 20:52 UTC by keshavbhatt

**What has changed:**

- do not control and report amavisd status if component is missing in case of single server clamav setup
- correctly report antivirus running for clamav only setups
- prevent parameter expansion eveywhere

see CO-597 for context.

2023-03-28 07:45 UTC, frisonisland approved these changes

2023-03-28 07:58 UTC, Polpetta approved these changes

2023-03-28 13:35 UTC, aheeva-yuliya approved these changes

2023-03-28 13:42 UTC, M0Rf30 commented
Idk if you noticed it, but zmantivirusctl != zmclamdctl

zmantivirus (as zmantispamctl) orchestrates the start / stop  of more than one service: zmamavisdctl zmclamdctl zmfreshclamctl

2023-03-28 14:06 UTC, frisonisland commented
> Idk if you noticed it, but zmantivirusctl != zmclamdctl
> 
> zmantivirusctl (as zmantispamctl) orchestrates the start / stop of more than one service: zmamavisdctl zmclamdctl zmfreshclamctl
> 
> So I expect conflicts during the start/stop of zmcontrol

So, mapping antivirus to zmclamdctl will result in starting/stopping only clamd service. This means freshclam and amavis will be up after antivirus is stopped.
Is any other service mapped to zmantivirusctl? If not who starts zmamavisdctl and zmfreshclamctl? :thinking:

2023-03-28 14:22 UTC, keshavbhatt commented
amavisd is managed with zmamavisdctl
clamd  is managed with zmclamdctl 
freshclamd  is managed with zmfreshclamctl.

In the past these three were defining the antivirus service and were managed together by zmantivirusctl. 

But thats no longer the case.

On a a single node clamav server,  zmantivirusctl wont report correct status of antivirus (clamav) as it depends on other services which do not exists there anymore example zmamavisdctl sill simply report incorrectly as logic is tied to existence of /opt/zextras/common/sbin/amavisd and so on...

we splited clamav, to separate service managed by zmclamdctl alone. Now the antivirus service represents the status of just clamav and not the combined status posted by zmantivirusctl.

2023-03-28 14:28 UTC, keshavbhatt commented
> only concern is freshclam

while testing i found freshclam is somehow getting started automatically. :D
I am investigating how.

2023-03-28 14:30 UTC, keshavbhatt commented
> Idk if you noticed it, but zmantivirusctl != zmclamdctl

I noticed it :100:

2023-03-29 08:21 UTC, keshavbhatt commented
> Idk if you noticed it, but zmantivirusctl != zmclamdctl
> 
> zmantivirusctl (as zmantispamctl) orchestrates the start / stop of more than one service: zmamavisdctl zmclamdctl zmfreshclamctl
> 
> So I expect conflicts during the start/stop of zmcontrol

Hi @M0Rf30 I have completely approached this issue in different way. It will not cause any issue you were concerned about. :)  I have udpated the description and title of PR to reflect what i changed.
Thanks for your valuable feedback. :heart:

2023-03-29 08:47 UTC, frisonisland requested changes
What I understand:
- if zmamavisdctl is not present then zmantivirusctl will skip it
- if zmamavisdctl is present, zmantivirusctl will start, reload/restart and check its status, but not stop it. -> Why amavis stop is not managed by zmantivirusctl? Service management looks confusing to me, I think it would be better to manage each service individually. Or separate amavis management from clamav + freshclam completely

2023-03-29 09:10 UTC, keshavbhatt commented
> * if zmamavisdctl is present, zmantivirusctl will start, reload/restart and check its status, but not stop it. -> Why amavis stop is not managed by zmantivirusctl? Service management looks confusing to me, I think it would be better to manage each service individually. Or separate amavis management from clamav + freshclam completely

I dont know why they do that atm, This logic was preserved from the old version of script. 

But lets remove this logic and see what potential damage it can do :D

2023-03-29 09:12 UTC, frisonisland commented
> 
> I dont know why they do that atm, This logic was preserved from the old version of script.

My other concern is who else manages amavis at this point. That's why I would propose keeping amavis separated from freshclam + clamav. @M0Rf30 any idea?

2023-03-29 09:20 UTC, keshavbhatt commented
I tested both zmcontrol and amantivirusctl both working fine. We are good.

2023-03-29 09:46 UTC, frisonisland approved these changes

2023-03-29 09:48 UTC, merged