fix: [CO-814] issue on configd service status check
zextras/carbonio-core-utils pull request #58
Opened 2023-08-02 10:42 UTC by M0Rf30

2023-08-02 12:18 UTC, mgarbin approved these changes

2023-08-02 12:24 UTC, frisonisland commented
Didn't we remove this behavior in https://github.com/zextras/carbonio-core-utils/commit/cdc9951466498ad422a7762badee4501e16309f9 for issues in redhat distros?

2023-08-02 12:27 UTC, M0Rf30 commented
Yes but cause of exit-status evalutation. The echo STATUS was giving empty responses because of the jython lib.
Because of merge squash I can't revert the single commit. So here we are

2023-08-03 06:09 UTC, frisonisland requested changes
We should explain the need of the change along with jython downgrade.
Is the current behavior not working?

We were informed of some issues in 23.7.0, but considering jython did not change at all from 23.6.0 to 23.7.0 it is very odd downgrading it.
The only yhing I am aware is the output may differ depending on netcat distributed version: nmap-ncat produced no output in my testing on Ubuntu 23.04, while openbsd netcat did print the expected "SUCCESS ACTIVE", so it may be a matter of ncat tool.
I ask also if it is possible to add some tests with a tool like: https://github.com/shellspec/shellspec

2023-08-03 08:49 UTC, keshavbhatt approved these changes

2023-08-03 08:50 UTC, frisonisland approved these changes

2023-08-03 09:05 UTC, merged